=== Kjawo/xml-zadanie-2/xml-zadanie-2/xml-zadanie-2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->
<!-- File: xml-zadanie-2.xsd -->
<!-- Authors: Konrad Jaworski, Tomasz Witczak -->
<!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->
<!-- TODO: trzeba dać jakoś nasze nazwy typów w jakiegoś namespace tak myślę -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified"
            attributeFormDefault="qualified">
    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- Root element -->
    <xsd:element name="bookStore" type="_bookStore" />

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- Document structure through types -->
    <!-- > bookStore -->
    <xsd:complexType name="_bookStore">
        <xsd:sequence>
            <xsd:element name="header" type="_header" />
            <xsd:element name="authors" type="_authors" />
            <xsd:element name="genres" type="_genres" />
            <xsd:element name="coverTypes" type="_coverTypes" />
            <xsd:element name="publishers" type="_publishers" />
            <xsd:element name="books" type="_books" />
        </xsd:sequence>
    </xsd:complexType>
    
    <!-- > header -->
    <xsd:complexType name="_header">
        <xsd:sequence>
            <xsd:element name="mainTitle" type="xsd:string" />
            <xsd:element name="description" type="xsd:string" />
            <xsd:element name="students" type="_students" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- > authors -->
    <xsd:complexType name="_authors">
        <xsd:sequence>
            <xsd:element name="author" type="_author" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- > genres -->
    <xsd:complexType name="_genres">
        <xsd:sequence>
            <xsd:element name="genre" type="genreType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- > coverTypes -->
    <xsd:complexType name="_coverTypes">
        <xsd:sequence>
            <xsd:element name="coverType" type="coverTypeType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- > publishers -->
    <xsd:complexType name="_publishers">
        <xsd:sequence>
            <xsd:element name="publisher" type="publisherType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- > books -->
    <xsd:complexType name="_books">
        <xsd:sequence>
            <xsd:element name="book" type="bookType" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
    <!-- Additional simple types -->
    <xsd:simpleType name="_name">               <!-- generic name type, first letter in uppercase -->
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="[A-Z][a-z]+" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:simpleType name="_studentNumber">      <!-- student number -->
        <xsd:restriction base="xsd:integer">
            <xsd:pattern value="[0-9]{6}" />
        </xsd:restriction>
    </xsd:simpleType>
    
    <xsd:simpleType name="_date">               <!-- date formatted like DAY-MONTH-YEAR -->
        <xsd:restriction base="xsd:string">
            <xsd:pattern value="([0][1-9]|[12][0-9]|[3][01])-([0][1-9]|[1][0-2])-([1-9][0-9]*)" />
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="_student">
        <xsd:sequence>
            <xsd:element name="firstName" type="_name" />
            <xsd:element name="lastName" type="_name" />
            <xsd:element name="indexNr" type="_studentNumber" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="_students">
        <xsd:sequence>
            <xsd:element name="student" type="_student" maxOccurs="unbounded" minOccurs="0"/>
        </xsd:sequence>
    </xsd:complexType>
    
   

    <!-- TODO -->
    <xsd:complexType name="_author">
        <xsd:sequence>
            <xsd:element name="firstName">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="Andrzej"/>
                        <xsd:enumeration value="Stephen"/>
                        <xsd:enumeration value="Umberto"/>
                        <xsd:enumeration value="Bolesław"/>
                        <xsd:enumeration value="George R.R."/>
                        <xsd:enumeration value="John"/>
                        <xsd:enumeration value="Henryk"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="lastName">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="Sapkowski"/>
                        <xsd:enumeration value="King"/>
                        <xsd:enumeration value="Eco"/>
                        <xsd:enumeration value="Prus"/>
                        <xsd:enumeration value="Martin"/>
                        <xsd:enumeration value="Green"/>
                        <xsd:enumeration value="Sienkiewicz"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="birthDate" type="_date" />
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="authorID" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="genreType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute type="xsd:string" name="genreID" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="coverTypeType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute type="xsd:string" name="coverTypeENUM" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="publisherType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute type="xsd:string" name="publisherID" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>

    <xsd:complexType name="frontCoverType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute type="xsd:string" name="src" use="optional"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
    <xsd:complexType name="bookType">
        <xsd:sequence>
            <xsd:element type="xsd:string" name="title"/>
            <xsd:element type="xsd:string" name="pages"/>
            <xsd:element type="xsd:string" name="publishYear"/>
            <xsd:element type="xsd:string" name="price"/>
            <xsd:element type="frontCoverType" name="frontCover"/>
            <xsd:element type="xsd:string" name="isbn"/>
        </xsd:sequence>
        <xsd:attribute type="xsd:string" name="bookID" use="optional"/>
        <xsd:attribute type="xsd:string" name="authorID" use="optional"/>
        <xsd:attribute type="xsd:string" name="genreID" use="optional"/>
        <xsd:attribute type="xsd:string" name="coverTypeENUM" use="optional"/>
        <xsd:attribute type="xsd:string" name="publisherID" use="optional"/>
    </xsd:complexType>
    <!-- TODO -->


    <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
</xsd:schema>
<!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->

=== Kjawo/xml-zadanie-2/xml-zadanie-2/xml-zadanie-2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->
<!-- File: xml-zadanie-2.xml -->
<!-- Authors: Konrad Jaworski, Tomasz Witczak -->
<!-- /////////////////////////////////////////////////////////////////////////////////////////////////////////////// -->
<bookStore xmlns="technologieXML-zad2-bookStore"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="technologieXML-zad2-bookStore xml-zadanie-2.xsd">
    <header>
        <mainTitle>INWENTARZ KSIĄŻEK</mainTitle>
        <description>Technologie XML - FTIMS 2018/19</description>
        <students>
            <student>
                <firstName>Konrad</firstName>
                <lastName>Jaworski</lastName>
                <indexNr>216782</indexNr>
            </student>
            <student>
                <firstName>Tomasz</firstName>
                <lastName>Witczak</lastName>
                <indexNr>216920</indexNr>
            </student>
        </students>
    </header>

    <authors>
        <author authorID="ASapkowski">
            <firstName>Andrzej</firstName>
            <lastName>Sapkowski</lastName>
            <birthDate>21-06-1948</birthDate>
        </author>
        <author authorID="SKing">
            <firstName>Stephen</firstName>
            <lastName>King</lastName>
            <birthDate>21-09-1947</birthDate>
        </author>
        <author authorID="UEco">
            <firstName>Umberto</firstName>
            <lastName>Eco</lastName>
            <birthDate>05-01-1932</birthDate>
        </author>
        <author authorID="BPrus">
            <firstName>Bolesław</firstName>
            <lastName>Prus</lastName>
            <birthDate>20-08-1847</birthDate>
        </author>
        <author authorID="GRRMartin">
            <firstName>George</firstName>
            <lastName>Martin</lastName>
            <birthDate>21-06-1948</birthDate>
        </author>
        <author authorID="JGreen">
            <firstName>John</firstName>
            <lastName>Green</lastName>
            <birthDate>24-08-1977</birthDate>
        </author>
        <author authorID="HSienkiewicz">
            <firstName>Henryk</firstName>
            <lastName>Sienkiewicz</lastName>
            <birthDate>05-05-1846</birthDate>
        </author>
    </authors>

    <genres>
        <genre genreID="fantasy">fantasy</genre>
        <genre genreID="horror">horror</genre>
        <genre genreID="kryminał">kryminał</genre>
        <genre genreID="powieść">powieść</genre>
    </genres>

    <coverTypes>
        <coverType coverTypeID="paperback">paperback</coverType>
        <coverType coverTypeID="hardback">hardback</coverType>
    </coverTypes>

    <publishers>
        <publisher publisherID="superNOWA">superNOWA</publisher>
        <publisher publisherID="Viking">Viking</publisher>
        <publisher publisherID="Doubleday">Doubleday</publisher>
        <publisher publisherID="Signet">Signet</publisher>
        <publisher publisherID="Bompiani">Bompiani</publisher>
        <publisher publisherID="Gebethner-Wolff">Gebethner-Wolff</publisher>
        <publisher publisherID="Zysk">Zysk</publisher>
        <publisher publisherID="Dutton">Dutton</publisher>
        <publisher publisherID="Greg">Greg</publisher>
    </publishers>

    <books>
        <book bookID="1" authorID="ASapkowski" genreID="fantasy"
              coverTypeID="paperback" publisherID="superNOWA">
            <title>Ostatnie Życzenie</title>
            <pages>288</pages>
            <publishYear>1993</publishYear>
            <price>35.99</price>
            <frontCover src="OstatnieZyczenie.jpg"/>
            <isbn>978-0-5754-08244-1</isbn>
        </book>
        <book bookID="2" authorID="ASapkowski" genreID="fantasy"
              coverTypeID="paperback" publisherID="superNOWA">
            <title>Miecz przeznaczenia</title>
            <pages>384</pages>
            <publishYear>1992</publishYear>
            <price>35.99</price>
            <frontCover src="MieczPrzeznaczenia.jpg"/>
            <isbn>978-1-4732-11532-7</isbn>
        </book>
        <book bookID="3" authorID="ASapkowski" genreID="fantasy"
              coverTypeID="hardback" publisherID="superNOWA">
            <title>Krew elfów</title>
            <pages>320</pages>
            <publishYear>1994</publishYear>
            <price>39.99</price>
            <frontCover src="KrewElfow.jpg"/>
            <isbn>978-0-5751-08484-1</isbn>
        </book>
        <book bookID="4" authorID="ASapkowski" genreID="fantasy"
              coverTypeID="paperback" publisherID="superNOWA">
            <title>Czas pogardy</title>
            <pages>352</pages>
            <publishYear>1995</publishYear>
            <price>35.99</price>
            <frontCover src="CzasPogardy.jpg"/>
            <isbn>978-0-5575-09094-1</isbn>
        </book>
        <book bookID="5" authorID="ASapkowski" genreID="fantasy"
              coverTypeID="paperback" publisherID="superNOWA">
            <title>Chrzest ognia</title>
            <pages>352</pages>
            <publishYear>1996</publishYear>
            <price>35.99</price>
            <frontCover src="ChrzestOgnia.jpg"/>
            <isbn>978-0-5475-09097-2</isbn>
        </book>
        <book bookID="6" authorID="ASapkowski" genreID="fantasy"
              coverTypeID="paperback" publisherID="superNOWA">
            <title>Wieża Jaskółki</title>
            <pages>462</pages>
            <publishYear>1997</publishYear>
            <price>35.99</price>
            <frontCover src="WiezaJaskolki.jpg"/>
            <isbn>978-0-5765-09083-3</isbn>
        </book>
        <book bookID="7" authorID="ASapkowski" genreID="fantasy"
              coverTypeID="paperback" publisherID="superNOWA">
            <title>Pani Jeziora</title>
            <pages>544</pages>
            <publishYear>1999</publishYear>
            <price>38.99</price>
            <frontCover src="PaniJeziora.jpg"/>
            <isbn>978-0-5758-09084-4</isbn>
        </book>
        <book bookID="8" authorID="SKing" genreID="horror"
              coverTypeID="paperback" publisherID="Viking">
            <title>It</title>
            <pages>1376</pages>
            <publishYear>1986</publishYear>
            <price>45.49</price>
            <frontCover src="It.jpg"/>
            <isbn>670-0-1234-81302-8</isbn>
        </book>
        <book bookID="9" authorID="SKing" genreID="horror"
              coverTypeID="paperback" publisherID="Doubleday">
            <title>The Shining</title>
            <pages>447</pages>
            <publishYear>1977</publishYear>
            <price>30.49</price>
            <frontCover src="TheShinning.jpg"/>
            <isbn>978-0-3875-12167-5</isbn>
        </book>
        <book bookID="10" authorID="SKing" genreID="fantasy"
              coverTypeID="hardback" publisherID="Signet">
            <title>The Green Mile</title>
            <pages>416</pages>
            <publishYear>1996</publishYear>
            <price>41.49</price>
            <frontCover src="TheGreenMile.jpg"/>
            <isbn>345-2-5258-67882-7</isbn>
        </book>
        <book bookID="11" authorID="UEco" genreID="kryminał"
              coverTypeID="hardback" publisherID="Bompiani">
            <title>The Name of the Rose</title>
            <pages>512</pages>
            <publishYear>1980</publishYear>
            <price>49.99</price>
            <frontCover src="TheNameoftheRose.jpg"/>
            <isbn>231-0-1455-14647-4</isbn>
        </book>
        <book bookID="12" authorID="BPrus" genreID="powieść"
              coverTypeID="paperback" publisherID="Gebethner-Wolff">
            <title>Lalka</title>
            <pages>664</pages>
            <publishYear>1890</publishYear>
            <price>23.23</price>
            <frontCover src="Lalka.jpg"/>
            <isbn>123-3-0551-05734-3</isbn>
        </book>
        <book bookID="13" authorID="GRRMartin" genreID="fantasy"
              coverTypeID="hardback" publisherID="Zysk">
            <title>A Game of Thrones</title>
            <pages>684</pages>
            <publishYear>1996</publishYear>
            <price>41.49</price>
            <frontCover src="AGameOfThrones.jpg"/>
            <isbn>657-0-5583-10354-7</isbn>
        </book>
        <book bookID="14" authorID="GRRMartin" genreID="fantasy"
              coverTypeID="paperback" publisherID="Zysk">
            <title>A Clash of Kings</title>
            <pages>768</pages>
            <publishYear>1999</publishYear>
            <price>35.49</price>
            <frontCover src="AClashOfKings.jpg"/>
            <isbn>845-0-5537-10803-4</isbn>
        </book>
        <book bookID="15" authorID="GRRMartin" genreID="fantasy"
              coverTypeID="hardback" publisherID="Zysk">
            <title>A Storm of Swords</title>
            <pages>973</pages>
            <publishYear>2000</publishYear>
            <price>39.99</price>
            <frontCover src="AStormOfSwords.jpg"/>
            <isbn>467-0-5538-10663-5</isbn>
        </book>
        <book bookID="16" authorID="GRRMartin" genreID="fantasy"
              coverTypeID="hardback" publisherID="Zysk">
            <title>A Feast for Crows</title>
            <pages>753</pages>
            <publishYear>2005</publishYear>
            <price>42.57</price>
            <frontCover src="AFeastForCrows.jpg"/>
            <isbn>757-0-5593-80150-3</isbn>
        </book>
        <book bookID="17" authorID="GRRMartin" genreID="fantasy"
              coverTypeID="hardback" publisherID="Zysk">
            <title>A Dance with Dragons</title>
            <pages>1056</pages>
            <publishYear>2011</publishYear>
            <price>55.67</price>
            <frontCover src="ADanceWithDragons.jpg"/>
            <isbn>636-0-5286-47181-7</isbn>
        </book>
